version: '3'
services:
  web:
    build: ./web
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/index.html:/var/www/html/index.html
      - ./web/page2.html:/var/www/html/page2.html
    ports:
      - "80:80"
    restart: always
  ssh:
    image: rastasheep/ubuntu-sshd:16.04
    volumes:
      - ./ssh/sshd_config:/etc/ssh/sshd_config:ro
    ports:
      - "4242:4242"
    restart: always
  tor:
    build: ./tor
    volumes:
      - ./tor/torrc:/etc/tor/torrc
    restart: always